---
- name: Create destination directory
  become: true
  file:
    path: /var/www/backend
    state: directory

- copy:
    src: /root/project/artifact.tar.gz
    dest: /var/www

- name: Extract the zipped artifact on the EC2 instance
  become: true
  unarchive:
    src: /var/www/artifact.tar.gz
    dest: "/var/www/backend"
    remote_src: true

- name: Install nodejs and npm
  apt:
    pkg:
      - nodejs
      - npm

- name: NODE | Install pm2
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Start Backend"
  shell: |
    cd /var/www/backend
    pm2 start npm --name backend -- start